function init(self)
	msg.post("@render:", "subscribe_screen_resized")
end

function final(self)
	msg.post("@render:", "unsubscribe_screen_resized")
end

function on_message(self, message_id, message)
	if message_id == hash("screen_resized") then
		local p = vmath.vector3(message.left, message.bottom, 0)
		local s = vmath.vector3(message.width, message.height, 0)
		if self.trigger ~= nil then go.delete(self.trigger) end
		self.trigger = factory.create("#factory", p, nil, nil, s)
	end
end
